### ISSUE TITLE
Error when precompiling assets

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#107]
Go to gems spec/test_app directory and run

`bundle exec rake assets:precompile`

You get 

```console
rake aborted!
SyntaxError: /Users/mitch/railsdev/reactive-ruby/lib/generators/reactive_ruby/test_app/templates/application.rb.erb:2: syntax error, unexpected tSTRING_BEG, expecting keyword_then or ';' or '\n'
_erbout.concat "require File.expand_path('../boot', __FILE__) \n"
                ^
/Users/mitch/railsdev/reactive-ruby/lib/generators/reactive_ruby/test_app/templates/application.rb.erb:15: syntax error, unexpected keyword_end, expecting end-of-input
/Users/mitch/.rvm/gems/ruby-2.2.2/gems/sprockets-3.5.2/lib/sprockets/erb_processor.rb:25:in `call'
/Users/mitch/.rvm/gems/ruby-2.2.2/gems/sprockets-3.5.2/lib/sprockets/erb_processor.rb:13:in `call'
/Users/mitch/.rvm/gems/ruby-2.2.2/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/mitch/.rvm/gems/ruby-2.2.2/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
```

**Comment by catmando** [comment]
This worked fine at this commit e2147320633f5981145063b86ad149d6a716ffd1

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#107
