### ISSUE TITLE
reactive-ruby branch: uninitialized constant React::Rails::ComponentMount (NameError)

### ISSUE THREAD

**Issue by MichaelSp** [zetachang/react.rb#72]
```
Error:[rake --tasks] /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails/component_mount.rb:3:in `<module:Rails>': uninitialized constant React::Rails::ComponentMount (NameError)
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails/component_mount.rb:2:in `<module:ReactiveRuby>'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails/component_mount.rb:1:in `<top (required)>'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails.rb:4:in `require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails.rb:4:in `<top (required)>'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby.rb:20:in `require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby.rb:20:in `<top (required)>'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `each'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `block in require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `each'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler.rb:134:in `require'
	from /home/michael/src/privat/SocialProjectsHub/config/application.rb:7:in `<top (required)>'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `preload'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:143:in `serve'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/michael/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by ajjahn** [comment]
@MichaelSp When are you seeing this error? Starting a rails server? Did you add `gem 'react-rails'` to your gem file? To use the rails component helpers, you need react-rails. It's not an explicit dependency because not everyone is using rails.

**Comment by MichaelSp** [comment]
Here is a minimal example: 
* `rails new example`
* Change Gemfile according to [Readme](https://github.com/zetachang/react.rb/tree/reactive-ruby)
* `rails s` and you'll see the backtrace.

Here is the example project: https://github.com/MichaelSp/reactive-ruby-example

**Comment by ajjahn** [comment]
@MichaelSp The isomorphic version of react-rails is no longer necessary. You gem file should include:
```
gem 'reactive-ruby', '~> 0.7.28'
gem 'react-rails', '~> 1.3.1'
gem 'opal-rails, '~> 0.8.0'
```

**Comment by MichaelSp** [comment]
Thanks that worked!

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#72
