### ISSUE TITLE
Gem wont precompile

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#82]
```
DEBUG [7eaa8815]     rake aborted!
DEBUG [7eaa8815]     An error occurred while compiling: generators/reactive_ruby/test_app/templates/application
DEBUG [7eaa8815]     
DEBUG [7eaa8815]     parse error on value "<" (tLT) :generators/reactive_ruby/test_app/templates/application:11
DEBUG [7eaa8815]     Source: generators/reactive_ruby/test_app/templates/application:11:1
DEBUG [7eaa8815]     <%= application_definition %>
DEBUG [7eaa8815]     ^
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/opal-0.8.1/lib/opal/parser.rb:48:in `rescue in parse'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/opal-0.8.1/lib/opal/parser.rb:33:in `parse'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/opal-0.8.1/lib/opal/compiler.rb:135:in `compile'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/opal-0.8.1/lib/opal/sprockets/processor.rb:52:in `evaluate'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/sprockets-3.4.0/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
DEBUG [7eaa8815]     /var/www/v4/shared/bundle/ruby/2.2.0/gems/sprockets-3.4.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
```

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#82
